import { NextResponse } from 'next/server'

import { verifyCron } from '@/lib/services/cron'
import { createDailyCronNotifications, listOperationRecipientIds } from '@/lib/services/notifications'
import { createAdminClient } from '@/lib/supabase/admin'

function isoWeekPeriod(date: Date) {
  const value = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()))
  const day = value.getUTCDay() || 7
  value.setUTCDate(value.getUTCDate() + 4 - day)
  const yearStart = new Date(Date.UTC(value.getUTCFullYear(), 0, 1))
  const week = Math.ceil(((value.getTime() - yearStart.getTime()) / 86_400_000 + 1) / 7)
  return `${value.getUTCFullYear()}-W${String(week).padStart(2, '0')}`
}

export async function GET(req: Request) {
  if (!verifyCron(req)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const admin = createAdminClient()
  const period = isoWeekPeriod(new Date())
  const { data: clients, error } = await admin
    .from('clients')
    .select('id, organization_id, name, organizations(slug)')
    .eq('status', 'active')

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  const reportRows = []

  for (const client of clients ?? []) {
    const { data: existing, error: existingError } = await admin
      .from('reports')
      .select('id')
      .eq('organization_id', client.organization_id)
      .eq('client_id', client.id)
      .eq('report_period', period)
      .eq('report_type', 'weekly')
      .maybeSingle()

    if (existingError) {
      return NextResponse.json({ error: existingError.message }, { status: 500 })
    }

    if (existing) continue

    reportRows.push({
      organization_id: client.organization_id,
      client_id: client.id,
      report_period: period,
      report_type: 'weekly',
      status: 'draft',
      notes: 'Weekly report draft generated by cron.'
    })
  }

  if (reportRows.length > 0) {
    const { error: insertError } = await admin.from('reports').insert(reportRows)
    if (insertError) {
      return NextResponse.json({ error: insertError.message }, { status: 500 })
    }
  }

  const notifications = []

  for (const client of clients ?? []) {
    const created = reportRows.some((row) => row.client_id === client.id && row.organization_id === client.organization_id)
    if (!created) continue

    const recipients = await listOperationRecipientIds(client.organization_id)
    const organization = Array.isArray(client.organizations) ? client.organizations[0] : client.organizations
    notifications.push(...recipients.map((userId) => ({
      organizationId: client.organization_id,
      userId,
      type: 'weekly_report_draft',
      title: 'Weekly report draft created',
      message: client.name,
      linkUrl: organization?.slug ? `/org/${organization.slug}/operation/reports` : undefined
    })))
  }

  const insertedNotifications = await createDailyCronNotifications(notifications)

  return NextResponse.json({ reports: reportRows.length, notifications: insertedNotifications })
}
