import { NextResponse } from 'next/server'

import { verifyCron } from '@/lib/services/cron'
import { createNotifications, listOperationRecipientIds } from '@/lib/services/notifications'
import { createAdminClient } from '@/lib/supabase/admin'

export async function GET(req: Request) {
  if (!verifyCron(req)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const admin = createAdminClient()
  const period = new Date().toISOString().slice(0, 10)
  const { data: clients, error } = await admin
    .from('clients')
    .select('id, organization_id, name, organizations(slug)')
    .eq('status', 'active')

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  const reportRows = (clients ?? []).map((client) => ({
    organization_id: client.organization_id,
    client_id: client.id,
    report_period: period,
    report_type: 'weekly',
    status: 'draft',
    notes: 'Weekly report draft generated by cron.'
  }))

  if (reportRows.length > 0) {
    await admin.from('reports').insert(reportRows)
  }

  const notifications = []

  for (const client of clients ?? []) {
    const recipients = await listOperationRecipientIds(client.organization_id)
    const organization = Array.isArray(client.organizations) ? client.organizations[0] : client.organizations
    notifications.push(...recipients.map((userId) => ({
      organizationId: client.organization_id,
      userId,
      type: 'weekly_report_draft',
      title: 'Weekly report draft created',
      message: client.name,
      linkUrl: organization?.slug ? `/org/${organization.slug}/operation/reports` : undefined
    })))
  }

  await createNotifications(notifications)

  return NextResponse.json({ reports: reportRows.length, notifications: notifications.length })
}
